apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 121304858170.dkr.ecr.ap-northeast-1.amazonaws.com/mybank:79dc1ec11685bfbb61b49d6a423c5665c35f31a4
        ports:
        - containerPort: 8080